### ISSUE TITLE
Optionally bypass stdout completely

### ISSUE THREAD

**Issue by oliversalzburg** [sfarthin/intercept-stdout#5]
It would be great if this module could optionally not write the captured data to stdout at all.

We use it to capture `console.log` output during testing. It would be nice if the captured log calls wouldn't pollute the output.

**Comment by bernardmcmanus** [comment]
@oliversalzburg +1, see this PR: https://github.com/sfarthin/intercept-stdout/pull/4. Nothing is printed if callback returns an empty string.

**Comment by sfarthin** [comment]
I merged @elnarddogg changes.

**Comment by oliversalzburg** [comment]
Awesome :) I'll give this a try right away

**Comment by bernardmcmanus** [comment]
thanks @sfarthin!

**Comment by oliversalzburg** [comment]
Works like a charm :)
